blog/urls.py
from django.contrib import admin
from django.contrib.staticfiles.views import serve
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from . import views


urlpatterns = [
    path('',views.home,name='home'),
    path('admin/', admin.site.urls),
    path('ckeditor',include('ckeditor_uploader.urls')),
    path('blog/',include('djangoBlog.urls'),name='blog'),
    path('comment/',include('comment.urls'),name='comment'),
    path('likes/',include('likes.urls'),name='likes'),
    path('user/',include('user.urls'),name='user'),
    path('captcha/',include('captcha.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

djangoBlog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path("",views.blog_list,name='blog_list'),
    path('<int:pk>',views.blog_detail,name="blog_detail"),
    path('type/<int:blog_type_pk>',views.blogs_with_type,name='blogs_with_type'),
    path('date/<int:year>/<int:month>',views.blogs_with_date,name="blogs_with_date"),
    path('tag/<int:blog_tag_pk>',views.blogs_with_tag,name='blogs_with_tag'),
    path('search/',views.search,name='search'),
    path('newblog/',views.NewBlogView.as_view(),name='new_blog'),
    path('updateblog/<int:pk>',views.UpdateBlogView.as_view(),name='update_blog'),

]

blog/views.py
import datetime
from django.shortcuts import render_to_response, render
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone
from django.db.models import Sum,Q
from django.core.cache import cache
from djangoBlog.models import Blog
from read_views.models import ReadNum
from read_views.utls import get_seven_days_read_data,get_today_hot_data



def get_7_days_hot_blogs():
    today = timezone.now().date()
    date = today - datetime.timedelta(days=7)
    blogs = Blog.objects.filter(read_details__date__lt=today,read_details__date__gt=date)\
        .values('id','title').annotate(read_num_sum=Sum('read_details__read_num')).order_by('-read_num_sum')[:7]
    return blogs


def home(request):
    blog_content_type = ContentType.objects.get_for_model(Blog)
    dates,read_nums = get_seven_days_read_data(blog_content_type)

    view_nums = ReadNum.objects.aggregate(Sum('read_num'))
    #获取七天热门文章的缓存数据
    hot_data_for_7_days = cache.get('hot_data_for_7_days')
    if hot_data_for_7_days is None:
        hot_data_for_7_days = get_7_days_hot_blogs()
        cache.set('hot_data_for_7_days',hot_data_for_7_days,3)
    context = {}
    # context['view_nums'] = view_nums['read_num__sum']
    context['read_nums'] = read_nums
    context['user'] = request.user
    context['dates'] = dates
    context['today_hot_date'] = get_today_hot_data(blog_content_type)
    context['hot_data_for_7_days'] = hot_data_for_7_days
    return render_to_response('home.html',context)

templates/blog/blog_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

    <div class="col-sm-9 col-md-9">
        <div class="list-title">
            <h4>{{ title }}</h4>
        </div>
        <article class="flex-left list-group-item post-item px-7">
            <div class="unit unit-1-on-mobile">
                <form action="" method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <p class="text-right">
                        <button class="btn btn-primary" type="submit" value="{{ button }}">{{ button }}</button>
                    </p>
                </form>
            </div>
        </article>
    </div>

{% endblock %}

{% block js %}

    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}

templates/blog/blog_list.html
{% extends 'base.html' %}

{% load blog_tags %}
{% load comment_tags %}

{% block title %}杨剑Blog|文章列表{% endblock %}


{% block nav_blog_active %}active{% endblock %}

{% block content %}
    <div class="col-sm-9 col-md-9">
        <div class="list-title">
            {% if blog_type %}
                {{ blog_type.type_name }}列表（共有{{ blogs.paginator.count }}篇文章）
            {% else %}
                文章列表（共有{{ blogs.paginator.count }}篇文章）
            {% endif %}
            {% if user.is_superuser %}
                <a href="{% url 'blog:new_blog' %}" class="pull-right"><i class="fas fa-pen-square" style="font-size: 1.5em"></i></a>
            {% endif %}
        </div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        <ul class="media-list">
            {% for blog in blogs.object_list %}
                <article class="flex-left list-group-item post-item px-7">
                    <div class="unit unit-1-on-mobile">
                        <h3 class="top-gap-0 post-item-title">
                            <a class="media-heading" href="{% url 'blog:blog_detail' blog.pk %}">{{ blog.title }}</a>
                            {% if user.is_superuser %}
                            <a href="{% url 'blog:update_blog' blog.pk %}" style="font-size: 15px;"> <i class="far fa-edit"></i></a>
                            {% endif %}
                        </h3>
                        <div class="media-body meta">
                            <span class="fa fa-user"
                                  aria-hidden="true"></span> {{ blog.author.get_nickname_or_username }}
                            <span> • </span>
                            <a href="{% url 'blog:blogs_with_type' blog.blog_type.pk %}">
                                <i class="fa fa-folder-open" aria-hidden="true"></i>
                                {{ blog.blog_type }}
                            </a>
                            <span> • </span>
                            <i class="fa fa-eye"></i> {{ blog.get_read_num }}
                            <span> • </span>
                            <span class="fa fa-comments"></span> {% get_comment_count blog %}
                            <span> • </span>
                            <span class="fa fa-calendar-alt"
                                  aria-hidden="true"></span> {{ blog.created_time | date:"Y-m-d H:i:s" }}
                        </div>
                    </div>
                </article>
                <div class="card-footer text-muted" style="background-color: #66CCFF;max-height: 2.8em">
{#              {{ blog.get_absolute_url }}          {% url 'blog_detail' blog.pk %}    #}
                    <p class="text-right"><a style="color: #FFFFFF;" href="{% url 'blog:blog_detail' blog.pk %} ">阅读文章</a></p>
                </div>
                <br>
            {% endfor %}
        </ul>
    {% include "_pagination.html" %}
    </div>
{% endblock %}

{% block tags %}
    <div class="col-sm-3 col-md-3 hidden-xs">
        <div class="card-header active-users" style="background-color: white;">
            <div class="text-center tag_title">博客分类</div>
            <hr>
            {% get_categories as blog_types %}
            {% for blog_type in blog_types %}
                <a class="media" href="{% url 'blog:blogs_with_type' blog_type.pk %}">
                    <div class="media-body">
                        <span class="media-heading">{{ blog_type.type_name }}
                            ({{ blog_type.num_blog_types }})</span>
                    </div>
                </a>
            {% empty %}
                <p>暂无分类</p>
            {% endfor %}
        </div>
        <br>
        <div class="card-header active-users" style="background-color: white;">
            <div class="text-center tag_title">日期归档</div>
            <hr>
            {% archives as blog_dates %}
            {% for blog_date in blog_dates %}
                <a class="media" href="{% url 'blog:blogs_with_date' blog_date.year blog_date.month %}">
                    <div class="media-body">
                        <span class="media-heading">{{ blog_date.year }}年{{ blog_date.month }}月</span>
                    </div>
                </a>
            {% empty %}
                <p>暂无归档</p>
            {% endfor %}
        </div>
        <br>
        <div class="card-header active-users" style="background-color: white;">
            <div class="text-center tag_title">标签云</div>
            <hr>
            {% get_tags as blog_tags %}

            <a class="media" href="#">
                <div class="media-body">
                    {% for blog_tag in blog_tags %}

                        <a href="{% url 'blog:blogs_with_tag' blog_tag.pk %}"
                           class="btn btn-outline-secondary btn-sm tag_a">{{ blog_tag.tag_name }}</a>
                    {% empty %}
                        <p>暂无标签</p>
                    {% endfor %}
                </div>
            </a>

        </div>
    </div>
{% endblock %}

templates/blog/blogs_with_type.html
{% extends 'blog/blog_list.html' %}
{% block title %}{{ blog_type.type_name }}{% endblock %}



{% block content %}
 <div class="col-sm-8 col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">{{ blog_type.type_name }}列表（共有{{ blogs.paginator.count }}篇文章）</div>
            <div class="panel-body">
                {% for blog in blogs.object_list %}
                    <a href="{% url 'blog_detail' blog.pk %}"><h3>{{ blog.title }}</h3></a>
                    <p>作者:{{ blog.author }}</p>
                    <p>发布日期：{{ blog.created_time | date:"Y-m-d H:nn:s" }}</p>
                    <p>分类：<a href="{% url 'blogs_with_type' blog.blog_type.pk %}">{{ blog.blog_type }}</a></p>
                    <p>{{ blog.content | truncatechars:40 }}</p>
                {% empty %}
                    <p>-- 暂无内容 --</p>
                {% endfor %}

            </div>
        </div>

{% include "_pagination.html" %}
    </div>

{% endblock %}