blog/urls.py
from django.contrib import admin
from django.contrib.staticfiles.views import serve
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from . import views


urlpatterns = [
    path('',views.home,name='home'),
    path('admin/', admin.site.urls),
    path('ckeditor',include('ckeditor_uploader.urls')),
    path('blog/',include('djangoBlog.urls'),name='blog'),
    path('comment/',include('comment.urls'),name='comment'),
    path('likes/',include('likes.urls'),name='likes'),
    path('user/',include('user.urls'),name='user'),
    path('captcha/',include('captcha.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

djangoBlog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path("",views.blog_list,name='blog_list'),
    path('<int:pk>',views.blog_detail,name="blog_detail"),
    path('type/<int:blog_type_pk>',views.blogs_with_type,name='blogs_with_type'),
    path('date/<int:year>/<int:month>',views.blogs_with_date,name="blogs_with_date"),
    path('tag/<int:blog_tag_pk>',views.blogs_with_tag,name='blogs_with_tag'),
    path('search/',views.search,name='search'),
    path('newblog/',views.NewBlogView.as_view(),name='new_blog'),
    path('updateblog/<int:pk>',views.UpdateBlogView.as_view(),name='update_blog'),

]

templates/_pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if blogs.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?{{ blogs.previous_page_number.querystring }}" tabindex="-1">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&laquo;</span>
            </li>
        {% endif %}

        {% for page_num in blogs.pages %}
            {% if page_num %}
                {% ifequal page_num blogs.number %}
                    <li class="page-item "><span></span></li>
                    <li class="page-item active"><a class="page-link">{{ page_num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?{{ page_num.querystring }}">{{ page_num }}</a>
                    </li>
                {% endifequal %}
            {% else %}
                <li class="page-item"><a class="page-link" href="#">...</a></li>
            {% endif %}
        {% endfor %}

        {% if blogs.has_next %}
            <li class="page-item">
                <a class="page-link" href="?{{ blogs.next_page_number.querystring }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&raquo;</span>
            </li>
        {% endif %}

    </ul>
</nav>

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}杨剑Blog{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
          integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link href="{% static '/css/base.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/prism.css' %}">

    {% block head_css %}

    {% endblock %}

<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?15a463fa63784bd7f58ae4c16128f794";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>


</head>
<body style="background-color: #f5f8fa">
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top navbar-dark bg-dark col-offset-1">
    <a class="navbar-brand" href="{% url "home" %}">
        杨剑Blog
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% block nav_home_active %}{% endblock %}">
                <a class="nav-link" href="/">首页</a>
            </li>
            <li class="nav-item {% block nav_blog_active %}{% endblock %}">
                <a class="nav-link" href="{% url 'blog:blog_list' %}">文章列表</a>
            </li>
        </ul>
        <div class="col-center-block">
            <form class="form-inline my-2 my-lg-0" action="{% url 'blog:search' %}" method="get">
                <input class="form-control mr-sm-2" name="search" id="search" type="search" placeholder="请输入文章标题"
                       aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>


        <ul class="nav navbar-nav navbar-right">
            {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}?from={{ request.get_full_path }}">登录</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}?from={{ request.get_full_path }}">注册</a>
                </li>
            {% else %}
                <li class="nav-item dropdown">

                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown">
                        <img src="{{ user.userprofile.image.url }}" class="rounded" alt="Cinque Terre" height="25px">
                        &nbsp;&nbsp;{{ user.get_nickname_or_username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'user_info' %}">个人资料</a>
                        <div class="dropdown-divider"></div>
                        {% if user.is_staff or user.is_superuser %}
                            <a class="dropdown-item" href="{% url 'admin:index' %}">后台管理</a>
                            <div class="dropdown-divider"></div>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'logout' %}?from={{ request.get_full_path }}">退出</a>
                    </div>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
    <div class="row">
        {% block content %}

        {% endblock %}
        {% block tags %}

        {% endblock %}

    </div>
    <div id="up-top">
        <i class="fas fa-caret-up"></i>
    </div>
</div>


<footer id="footer" class="text-center">
    <div class="copyright">
        <span>博客总访问量：{% get_view_nums %}</span>
    </div>
    <div class="copyright-1">
        <a href="http://www.miitbeian.gov.cn" style="color: white">蜀ICP备17019633号</a>
    </div>
</footer>


</body>

<script src="https://cdn.hcharts.cn/highcharts/highcharts.js"></script>
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'js/blog.js' %}"/>
<script src="https://cdn.bootcss.com/popper.js/1.14.3/umd/popper.min.js" type="text/javascript"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

<script>
    // 图表配置
    var options = {
        chart: {
            type: 'line'                          //指定图表的类型，默认是折线图（line）
        },
        title: {
            text: '最近一周访问量'                 // 标题
        },
        xAxis: {
            categories: {{ dates | safe }},   // x 轴分类
            tickmarkPlacement: 'on'
        },
        yAxis: {
            title: {
                text: null                // y 轴标题
            },
            labels: {enabled: false},
            gridLineDashStyle: 'Dash',
        },
        series: [{                              // 数据列
            name: '访问量',                        // 数据列名
            data: {{ read_nums }}                     // 数据
        }],

        legend: {enabled: false},
        credits: {enabled: false},
    };
    // 图表初始化函数
    var chart = Highcharts.chart('container', options);
</script>

<script type="text/javascript" src="{% static 'ckeditor/static/ckeditor/ckeditor/plugins/prism_patched.min.js' %}"/>


{% block js %}

{% endblock %}
</html>

templates/error.html
{% extends 'base.html' %}
{% block title %}错误提示{% endblock %}
{% block content %}
    {{ message }},<a href="{{ redirect_to }}">返回</a>
{% endblock %}

templates/form.html
{% extends 'base.html' %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
    <div class="col-sm-8 col-md-8">
        <div class="card">
            <h4 class="card-header">{{ form_title }}</h4>
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if not field.is_hidden %}
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {% endif %}
                        {{ field }}
                        <p class="text-danger">{{ field.errors.as_text }}</p>
                    {% endfor %}
                    <span id="tip" class="pull-left text-danger">{{ form.non_field_errors }}</span>
                    <div class="clearfix"></div>
                    <div class="text-right">
                        {% block other_buttons %}{% endblock %}
                        <button class="btn btn-primary " type="submit"
                                value="{{ submit_text }}">{{ submit_text }}</button>
                        <button class="btn btn-default" onclick="window.location.href='{{ return_back_url }}'">返回
                        </button>

                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

templates/home.html
{% extends 'base.html' %}


{% block title %}杨剑Blog|首页{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="col-sm-9 col-md-9">
        <div>
            <h3 class="home-content">欢迎访问我的个人博客</h3>
            <!-- 图表容器 DOM -->
            <div class="viewsDOM" id="container"></div>
        </div>
    </div>
    <div class="col-sm-3 col-md-3">
        <div class="card-header active-users" style="background-color: white;">
            <div class="text-center tag_title">今天热门文章</div>
            <hr>
            {% for hot_date in today_hot_date %}
                <a class="media" href="{% url 'blog:blog_detail' hot_date.content_object.pk %}">
                    <div class="media-body">
                        <span class="media-heading">{{ hot_date.content_object.title | truncatechars:25 }}
                        </span>
                    </div>
                </a>
            {% empty %}
                <p>今天暂时没有热门文章</p>
            {% endfor %}
        </div>
        <br>
        <div class="card-header active-users" style="background-color: white;">
            <div class="text-center tag_title">七天热门文章</div>
            <hr>
            {% for hot_blog in hot_data_for_7_days %}
                <a class="media" href="{% url 'blog:blog_detail' hot_blog.id %}">
                    <div class="media-body">
                        <span class="media-heading">{{ hot_blog.title | truncatechars:25 }}
                        </span>
                    </div>
                </a>
            {% empty %}
                <p>七天暂时没有热门文章</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block js %}


{% endblock %}